declare module "react-router-dom"
declare module "redux-thunk"
declare module "quill-image-uploader"
declare module "quill-image-resize-module"
declare module "react-use/lib/useWindowSize"
declare module "react-redux"
declare module "editorjs-parser"
declare module "redux-persist"
declare module "redux-persist/lib/storage"
declare module "@ckeditor/ckeditor5-react"
declare module "@ckeditor/ckeditor5-core/src/context"
declare module "@ckeditor/ckeditor5-editor-classic/src/classiceditor"
declare module "@ckeditor/ckeditor5-build-classic"
declare module "@ckeditor/ckeditor5-easy-image/src/easyimage"
declare module "quill-image-resize-module-react"
declare module "react-ckeditor-component"
declare module '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
declare module '@ckeditor/ckeditor5-alignment/src/alignment.js';
declare module '@ckeditor/ckeditor5-image/src/autoimage.js';
declare module '@ckeditor/ckeditor5-autoformat/src/autoformat.js';
// declare module   '@ckeditor/ckeditor5-block-quote/src/blockquote.js';
declare module '@ckeditor/ckeditor5-basic-styles/src/bold.js';
declare module  '@ckeditor/ckeditor5-essentials/src/essentials.js';
declare module  '@ckeditor/ckeditor5-font/src/fontsize.js';
declare module  '@ckeditor/ckeditor5-heading/src/heading.js';
declare module  '@ckeditor/ckeditor5-horizontal-line/src/horizontalline.js';
declare module '@ckeditor/ckeditor5-html-embed/src/htmlembed.js';
declare module '@ckeditor/ckeditor5-image/src/image.js';
declare module  '@ckeditor/ckeditor5-image/src/imagecaption.js';
declare module  '@ckeditor/ckeditor5-image/src/imageresize.js';
declare module  '@ckeditor/ckeditor5-image/src/imagestyle.js';
declare module  '@ckeditor/ckeditor5-image/src/imagetoolbar.js';
declare module  '@ckeditor/ckeditor5-image/src/imageupload.js';
declare module  '@ckeditor/ckeditor5-indent/src/indent.js';
declare module  '@ckeditor/ckeditor5-basic-styles/src/italic.js';
declare module  '@ckeditor/ckeditor5-link/src/link.js';
declare module  '@ckeditor/ckeditor5-list/src/list.js';
declare module  '@ckeditor/ckeditor5-media-embed/src/mediaembed.js';
declare module  '@ckeditor/ckeditor5-paragraph/src/paragraph.js';
declare module  '@ckeditor/ckeditor5-paste-module-office/src/pastefromoffice.js';
declare module  '@ckeditor/ckeditor5-table/src/table.js';
declare module  '@ckeditor/ckeditor5-table/src/tabletoolbar.js';
declare module  '@ckeditor/ckeditor5-typing/src/texttransformation.js';
declare module  'ckeditor5-custom-build/build/ckeditor';



declare  module '@ckeditor/ckeditor5-autoformat/src/autoformat';
declare  module '@ckeditor/ckeditor5-image/src/autoimage';
declare  module '@ckeditor/ckeditor5-link/src/autolink';
declare  module '@ckeditor/ckeditor5-block-quote/src/blockquote';
declare  module '@ckeditor/ckeditor5-basic-styles/src/bold';
declare  module '@ckeditor/ckeditor5-upload/src/adapters/base64uploadadapter';
declare  module '@ckeditor/ckeditor5-cloud-services/src/cloudservices';
declare  module '@ckeditor/ckeditor5-basic-styles/src/code';
declare  module '@ckeditor/ckeditor5-code-block/src/codeblock';
declare  module '@ckeditor/ckeditor5-essentials/src/essentials';
declare  module '@ckeditor/ckeditor5-export-pdf/src/exportpdf';
declare  module '@ckeditor/ckeditor5-export-word/src/exportword';
declare  module '@ckeditor/ckeditor5-declare-word/src/importword';
declare  module '@ckeditor/ckeditor5-find-and-replace/src/findandreplace';
declare  module '@ckeditor/ckeditor5-font/src/font';
declare  module '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport';
declare  module '@ckeditor/ckeditor5-heading/src/heading';
declare  module '@ckeditor/ckeditor5-horizontal-line/src/horizontalline';
declare  module '@ckeditor/ckeditor5-html-embed/src/htmlembed';
declare  module '@ckeditor/ckeditor5-image/src/image';
declare  module '@ckeditor/ckeditor5-image/src/imagecaption';
declare  module '@ckeditor/ckeditor5-image/src/imageinsert';
declare  module '@ckeditor/ckeditor5-image/src/imageresize';
declare  module '@ckeditor/ckeditor5-image/src/imagestyle';
declare  module '@ckeditor/ckeditor5-image/src/imagetoolbar';
declare  module '@ckeditor/ckeditor5-image/src/imageupload';
declare  module '@ckeditor/ckeditor5-indent/src/indent';
declare  module '@ckeditor/ckeditor5-indent/src/indentblock';
declare  module '@ckeditor/ckeditor5-basic-styles/src/italic';
declare  module '@ckeditor/ckeditor5-link/src/link';
declare  module '@ckeditor/ckeditor5-link/src/linkimage';
declare  module '@ckeditor/ckeditor5-list/src/list';
declare  module '@ckeditor/ckeditor5-list/src/listproperties';
declare  module '@ckeditor/ckeditor5-media-embed/src/mediaembed';
declare  module '@ckeditor/ckeditor5-mention/src/mention';
declare  module '@ckeditor/ckeditor5-page-break/src/pagebreak';
declare  module '@ckeditor/ckeditor5-paragraph/src/paragraph';
declare  module '@ckeditor/ckeditor5-paste-module-office/src/pastefromoffice';
declare  module '@ckeditor/ckeditor5-image/src/pictureediting';
declare  module '@ckeditor/ckeditor5-remove-format/src/removeformat';
declare  module '@ckeditor/ckeditor5-source-editing/src/sourceediting';
declare  module '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
declare  module '@ckeditor/ckeditor5-style/src/style';
declare  module '@ckeditor/ckeditor5-basic-styles/src/subscript';
declare  module '@ckeditor/ckeditor5-basic-styles/src/superscript';
declare  module '@ckeditor/ckeditor5-table/src/table';
declare  module '@ckeditor/ckeditor5-table/src/tablecaption';
declare  module '@ckeditor/ckeditor5-table/src/tablecellproperties';
declare  module '@ckeditor/ckeditor5-table/src/tablecolumnresize';
declare  module '@ckeditor/ckeditor5-table/src/tableproperties';
declare  module '@ckeditor/ckeditor5-table/src/tabletoolbar';
declare  module '@ckeditor/ckeditor5-language/src/textpartlanguage';
declare  module '@ckeditor/ckeditor5-typing/src/texttransformation';
declare  module '@ckeditor/ckeditor5-list/src/todolist';
declare  module '@ckeditor/ckeditor5-basic-styles/src/underline';
declare  module '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
declare  module '@webspellchecker/wproofreader-ckeditor5/src/wproofreader';
declare  module '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
declare  module '@ckeditor/ckeditor5-import-word/src/importword';

